### ISSUE TITLE
Thanks, a couple of nits and 3 corrections

### ISSUE THREAD

**Issue by mhodapp** [opensourceway/rsync-backup-script#1]
I have been experimenting with rsbu for my home network and have come up with the following issues with the code. And maybe you should remind rsync users that hardlinks are not supported on NTFS.

line 104, should refer to unmount:
   echo "u     Verbose mode."

*******************************************************************************************

line 115, spelling of "history":
   echo "existing set of backup files and do not create a backup hiistory."

*******************************************************************************************

lines 610-616:
               if [ $TestMode = 0 ]
               then 
                  if [ $verbose = 1 ]
                  then
                     echo "Not test mode. We ARE performing the backup."
                     rsync -aH -e ssh --delete --link-dest=$LastBackupPath $Excludes $HostName$BackupData $TodaysBackupPath
                  fi

should be:
               if [ $TestMode = 0 ]
               then 
                  if [ $verbose = 1 ]
                  then
                     echo "Not test mode. We ARE performing the backup."
                  fi
               rsync -aH -e ssh --delete --link-dest=$LastBackupPath $Excludes $HostName$BackupData $TodaysBackupPath

*******************************************************************************************

lines 637-643:
               if [ $TestMode = 0 ]
               then 
                  if [ $verbose = 1 ]
                  then
                     echo "Not test mode. We ARE performing the backup."
                     rsync -aH --delete $Excludes $HostName$BackupData $TodaysBackupPath
                  fi

should be:

               if [ $TestMode = 0 ]
               then 
                  if [ $verbose = 1 ]
                  then
                     echo "Not test mode. We ARE performing the backup."
                  fi
               rsync -aH --delete $Excludes $HostName$BackupData $TodaysBackupPath

*******************************************************************************************

lines 656-662:
               if [ $TestMode = 0 ]
               then 
                  if [ $verbose = 1 ]
                  then
                     echo "Not test mode. We ARE performing the backup."
                     rsync -aH -e ssh --delete $Excludes $HostName$BackupData $TodaysBackupPath
                  fi

should be:

               if [ $TestMode = 0 ]
               then 
                  if [ $verbose = 1 ]
                  then
                     echo "Not test mode. We ARE performing the backup."
                  fi
               rsync -aH -e ssh --delete $Excludes $HostName$BackupData $TodaysBackupPath

**Comment by mbbroberg** [comment]
Thanks for the comments here. The author is not intending to update further, but feel free to fork and respin however you'd like :+1:
